from datetime import datetime
from typing import Optional

from sqlalchemy import Index
from sqlmodel import Field

from .base import SQLModel


class SecureToken(SQLModel, table=True):
    """
    Database model for one-time secure tokens.

    This model stores temporary security tokens used for sensitive user flows
    such as password resets and future verification mechanisms.

    Attributes
    ----------
    id : int | None
        Primary key identifier for the secure token (internal use only).
        Auto-generated by the database.
    user_id : int
        Foreign key reference to the associated user (`users.id`).
        Used to link tokens to a specific account.
        Indexed for fast lookup operations.
    token : str
        Hashed representation of the secure token.
        The plaintext token is never stored in the database for security reasons.
    used : bool, default=False
        Indicates whether the token has already been consumed.
        Enforces single-use token behavior.
    expires_at : datetime
        UTC timestamp indicating when the token becomes invalid.
        Expired tokens must not be accepted during validation.
    created_at : datetime
        Timestamp indicating when the token was generated.
        Useful for auditing and cleanup operations.

    Notes
    -----
    - Tokens must always be stored in hashed form.
    - Tokens are single-use and must be marked as used after successful validation.
    - Expiration should always be validated at application level.
    - Designed to support future flows such as email verification or account recovery.
    """

    __tablename__ = "secure_token"

    # Composite index optimized for validation queries
    __table_args__ = (
        Index(
            "ix_secure_tokens_token_used",
            "token",
            "used",
        ),
    )

    id: Optional[int] = Field(default=None, primary_key=True)

    user_id: int = Field(
        foreign_key="users.id",
        nullable=False,
        index=True,
    )

    token: str = Field(
        nullable=False,
        description="Hashed secure token value",
    )

    used: bool = Field(
        default=False,
        nullable=False,
    )

    expires_at: datetime = Field(
        nullable=False,
    )

    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        nullable=False,
    )


# Register model for SQLModel metadata discovery (Alembic autogenerate)
__all__ = [
    "SecureToken",
]
