import uuid

from pydantic import EmailStr
from sqlmodel import Boolean, Field, Integer

from auth.types.enums import AuthType, UserType

from .base import SQLModel


# Database model, database table inferred from class name
class Users(SQLModel, table=True):
    """
    Database model for user accounts.

    This model defines the schema for storing user data in the database.

    Attributes
    ----------
    id : int | None
        Primary key identifier for the user (internal use only).
        Auto-generated by the database.
    guid : uuid.UUID
        Globally unique identifier (UUID4) for the user. Auto-generated on
        creation. Safe for external sharing and API responses. Indexed and
        unique.
    email : EmailStr
        User's email address. Used for authentication and communication.
        Must be unique and valid email format. Maximum 255 characters.
        Indexed for fast lookups.
    username : str
        Unique username chosen by the user for login and display purposes.
        Maximum 255 characters. Indexed for fast lookups.
    first_name : str | None, optional
        User's first name. Maximum 255 characters.
    last_name : str | None, optional
        User's last name. Maximum 255 characters.
    password : str | None, optional
        Hashed password for manual authentication. Null for OAuth/SSO users.
        Maximum 255 characters. Never store plain text passwords.
    auth_type : AuthType, default=AuthType.MANUAL
        Authentication method used by the user. Enum representing different
        authentication strategies (e.g., MANUAL, GOOGLE, FACEBOOK, X). Stored as an
        integer in the database.
    role : UserType, default=UserType.CUSTOMER
        User's role in the system for permission management. Enum defining
        access levels (e.g., ADMIN, OWNER, MANAGER, CUSTOMER). Stored as an
        integer in the database.
    is_email_verified : bool, default=False
        Whether the user's email address has been verified. Used to enforce
        email verification workflows.
    is_active : bool, default=False
        Whether the user account is currently active. Inactive users cannot
        log in or access the system.
    is_deleted : bool, default=False
        Soft delete flag. Deleted users are retained in the database but
        hidden from normal operations.

    Examples
    --------
    >>> # Create a new owner user
    >>> user = Users(
    ...     email="smit.patel@example.com",
    ...     first_name="Smit",
    ...     last_name="Patel",
    ...     password=hash_password("secure_password"),
    ...     auth_type=AuthType.MANUAL,
    ...     role=UserType.OWNER
    ... )

    >>> # Create an Google user (no password)
    >>> google_user = Users(
    ...     email="smit.patel@example.com",
    ...     first_name="Smit",
    ...     last_name="Patel",
    ...     auth_type=AuthType.GOOGLE,
    ...     role=UserType.OWNER, # Third party user authentication can only be owner
    ...     is_active=True
    ... )

    Notes
    -----
    - Always use `guid` for external references and API responses
    - Use `id` only for internal database operations and relationships
    - Indexed fields (`id`, `guid`, `email`) enable fast queries
    """

    id: int | None = Field(default=None, primary_key=True, index=True)
    guid: uuid.UUID = Field(default_factory=uuid.uuid4, unique=True, nullable=False, index=True)
    email: EmailStr = Field(unique=True, index=True, max_length=255)
    username: str = Field(unique=True, index=True, max_length=255)
    first_name: str | None = Field(default=None, max_length=255)
    last_name: str | None = Field(default=None, max_length=255)
    password: str | None = Field(default=None, max_length=255)
    auth_type: AuthType = Field(default=AuthType.MANUAL, nullable=False, sa_type=Integer)
    role: UserType = Field(default=UserType.CUSTOMER, nullable=False, sa_type=Integer)
    is_active: bool = Field(default=False, nullable=False, sa_type=Boolean)
    is_deleted: bool = False


# List all database model classes defined in this file.
# These models are imported when the database module is loaded,
# registering their tables in SQLModel.metadata.
# This is required for Alembic to automatically detect schema changes
# and generate migrations.
__all__ = [
    "Users"
]
