"""add email verification otp

Revision ID: ac6509a33344
Revises: c11bd244d058
Create Date: 2026-08-12 02:21:49.553090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ac6509a33344'
down_revision: Union[str, Sequence[str], None] = 'c11bd244d058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_user_id'), 'otp', ['user_id'], unique=False)

    op.add_column(
        "users",
        sa.Column("is_email_verified", sa.Boolean(), nullable=True),
    )

    op.execute(
        "UPDATE users SET is_email_verified = FALSE "
        "WHERE is_email_verified IS NULL"
    )

    op.alter_column(
        "users",
        "is_email_verified",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_email_verified')
    op.drop_index(op.f('ix_otp_user_id'), table_name='otp')
    op.drop_table('otp')
    # ### end Alembic commands ###
