"""create secure token

Revision ID: c11bd244d058
Revises: c68e3c9a9fc9
Create Date: 2026-02-21 06:33:32.893694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c11bd244d058'
down_revision: Union[str, Sequence[str], None] = 'c68e3c9a9fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secure_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secure_token_user_id'), 'secure_token', ['user_id'], unique=False)
    op.create_index('ix_secure_tokens_token_used', 'secure_token', ['token', 'used'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_secure_tokens_token_used', table_name='secure_token')
    op.drop_index(op.f('ix_secure_token_user_id'), table_name='secure_token')
    op.drop_table('secure_token')
    # ### end Alembic commands ###
