"""add user id to usersreplica

Revision ID: 6236ca5642cf
Revises: e6ef4738e2d0
Create Date: 2026-08-17 02:30:49.303193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6236ca5642cf'
down_revision: Union[str, Sequence[str], None] = 'e6ef4738e2d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersreplica', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_usersreplica_user_id'), 'usersreplica', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usersreplica_user_id'), table_name='usersreplica')
    op.drop_column('usersreplica', 'user_id')
    # ### end Alembic commands ###
