"""create user replica table

Revision ID: a5f02c467b7d
Revises: 
Create Date: 2026-08-15 07:08:31.990149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a5f02c467b7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersreplica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usersreplica_email'), 'usersreplica', ['email'], unique=True)
    op.create_index(op.f('ix_usersreplica_guid'), 'usersreplica', ['guid'], unique=True)
    op.create_index(op.f('ix_usersreplica_id'), 'usersreplica', ['id'], unique=False)
    op.create_index(op.f('ix_usersreplica_username'), 'usersreplica', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usersreplica_username'), table_name='usersreplica')
    op.drop_index(op.f('ix_usersreplica_id'), table_name='usersreplica')
    op.drop_index(op.f('ix_usersreplica_guid'), table_name='usersreplica')
    op.drop_index(op.f('ix_usersreplica_email'), table_name='usersreplica')
    op.drop_table('usersreplica')
    # ### end Alembic commands ###
