import uuid

from pydantic import EmailStr
from sqlmodel import Field

from .base import SQLModel


# Database model, database table inferred from class name
class UsersReplica(SQLModel, table=True):
    """
    Database model for user replicated user data from auth service.

    This model defines the schema for storing replicated user data from auth service in the database.

    Attributes
    ----------
    id : int | None
        Primary key identifier for the replicated user data (internal use only).
        Auto-generated by the database.
    guid : uuid.UUID
        Globally unique identifier (UUID4) for the user. Auto-generated on
        creation. Safe for external sharing and API responses. Indexed and
        unique.
    email : EmailStr
        User's email address. Used for authentication and communication.
        Must be unique and valid email format. Maximum 255 characters.
        Indexed for fast lookups.
    username : str
        Unique username chosen by the user for login and display purposes.
        Maximum 255 characters. Indexed for fast lookups.
    first_name : str | None, optional
        User's first name. Maximum 255 characters.
    last_name : str | None, optional
        User's last name. Maximum 255 characters.

    Notes
    -----
    - Always use `guid` for external references and API responses
    - Use `id` only for internal database operations and relationships
    - Indexed fields (`id`, `guid`, `email`) enable fast queries
    """

    __tablename__ = "usersreplica"

    id: int | None = Field(default=None, primary_key=True, index=True)
    guid: uuid.UUID | None = Field(default_factory=uuid.uuid4, unique=True, nullable=False, index=True)
    email: EmailStr = Field(unique=True, index=True, max_length=255)
    username: str = Field(unique=True, index=True, max_length=255)
    first_name: str | None = Field(default=None, max_length=255)
    last_name: str | None = Field(default=None, max_length=255)


# List all database model classes defined in this file.
# These models are imported when the database module is loaded,
# registering their tables in SQLModel.metadata.
# This is required for Alembic to automatically detect schema changes
# and generate migrations.
__all__ = [
    "UsersReplica"
]
