from pydantic import EmailStr

from auth.types.enums import UserType

from .base_schemas import BaseSchema


class UserSignup(BaseSchema):
    first_name: str
    last_name: str
    email: EmailStr
    username: str
    password: str


class UserCreateRequest(BaseSchema):
    """
    Payload for creating a user by an authorized admin/owner/manager.

    Password is generated by the backend and delivered via welcome email.
    """

    first_name: str
    last_name: str
    email: EmailStr
    username: str


class ProfileData(BaseSchema):
    email: EmailStr
    username: str
    role: UserType
    guid: str
    first_name: str | None = None
    last_name: str | None = None
    is_email_verified: bool = False


class ProfileUpdate(BaseSchema):
    username: str
    first_name: str
    last_name: str


class UserUpdateRequest(ProfileUpdate):
    """
    Payload for updating a provisioned user by an authorized actor.

    GUID identifies the target user and is sent in the body, not the URL.
    """

    guid: str


class ChangePassword(BaseSchema):
    current_password: str
    new_password: str


class VerifyEmailOtpRequest(BaseSchema):
    otp: str
