# Description: Generates database migration scripts by detecting schema changes using Alembic's
#              automatic migration feature.
# Argument: Name of the FastAPI application.
# Expected User Input at Runtime: A migration message to append to the generated script name.
# Output: None
# Process: Automatically generates a migration script for the specified application based on
#          detected database schema changes.

# ***************************************************************
# ***************** Helper methods and sources ******************
# ***************************************************************
# Source utils script
source ./utils.sh


# Function to get user message
getMessageFormUserToGenerateMigration() {
    # Description: Prompts the user to enter a descriptive, human-readable message
    #              for the Alembic migration to ensure meaningful migration history.
    # Parameters: None
    # Returns: The user-provided migration message (read from stdin)
    local message=""

    # echo -n "Please enter your migration message: "
    read -r -p "Please enter migration message: " message

    askForApprovalToGenerateMigrationWithoutMessage() {
        if [[ -z "$message" || "$message" == "" ]]; then
            local reply=""
            read -r -p "Are you sure you want to generate migration without message(yes/no): " reply

            reply=${reply,,}

            if [[ $reply == "no" || $reply == "n" ]]; then
                # If user denied to generate migration without message
                # Then ask user to add message again
                getMessageFormUserToGenerateMigration
            elif [[ $reply == "yes" || $reply == "y" ]]; then
                # If user want to generate migration without message then
                # allow user to generate migration without message
                printWarningText "Generating migration without migration message."
            else
                echo "Please enter correct response"
                askForApprovalToGenerateMigrationWithoutMessage
            fi
        fi
    }

    # If the migration message is empty, confirm whether this is intentional.
    askForApprovalToGenerateMigrationWithoutMessage

    # Return user entereed migrarion message
    echo $message
}
# ************** End **************


# ***************************************************************
# ************************ Declarations *************************
# ***************************************************************

# Base path of services directory
BASE_PATH=/workspace/backend/services

# Get FastAPI app name specified in arguement
APP=$1
# ************** End **************

# Set path based on the application name
if [[ $APP == "auth" ]]; then
    echo "Set path for the AUTH app!"
    APP_PATH="$BASE_PATH/auth/auth/database"
elif [[ $APP == "booking" ]]; then
    echo "Set path for the BOOKING app!"
    APP_PATH="$BASE_PATH/booking/booking/database"
elif [[ $APP == "payment" ]]; then
    echo "Set path for the PAYMENT app!"
    APP_PATH="$BASE_PATH/payment/payment/database"
# Add conditions to get path for another apps
# elif [[ "$APP" -eq "anotherApp" ]] then
#     another path
else
    printErrorText "Invalid application name provided."
    exit 1
fi

# Naviagate to data directory path of specified application
echo "Navigating to database directory of respective application"
cd $APP_PATH

# Ask the user for a relevant message to generate the migration.
message=$(getMessageFormUserToGenerateMigration)

# Generating the migration
echo "Generating migration..."
uv run alembic revision --autogenerate -m "$message"

# Verify whether migration created successfully or not
if [ $? -eq 0 ]; then
    printSuccessText "Autogenerated migration for ${reply^^} created successfully!"
else
    printErrorText "Unexpected error occur while generating migration!"
fi